### ISSUE TITLE
Crash while serializing

### ISSUE THREAD

**Issue by douglas-raillard-arm** [DataEngineeringLabs/arrow2-convert#86]
```
thread 'main' panicked at 'attempt to subtract with overflow', src/analysis/tasks.rs:270:75
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e0098a5cc3a87d857e597af824d0ce1ed1ad85e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/e0098a5cc3a87d857e597af824d0ce1ed1ad85e0/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/e0098a5cc3a87d857e597af824d0ce1ed1ad85e0/library/core/src/panicking.rs:114:5
   3: <lisa_rust_analysis::analysis::tasks::MutableTaskStateArray as arrow2::array::TryPush<core::option::Option<__T>>>::try_push
             at ./tools/analysis/src/analysis/tasks.rs:270:75
   4: <lisa_rust_analysis::analysis::tasks::TaskState as arrow2_convert::serialize::ArrowSerialize>::arrow_serialize
             at ./tools/analysis/src/analysis/tasks.rs:270:75
   5: <lisa_rust_analysis::analysis::tasks::MutableTasksStatesRowArray as arrow2::array::TryPush<core::option::Option<__T>>>::try_push
             at ./tools/analysis/src/analysis/tasks.rs:575:24
   6: <lisa_rust_analysis::analysis::tasks::TasksStatesRow as arrow2_convert::serialize::ArrowSerialize>::arrow_serialize
             at ./tools/analysis/src/analysis/tasks.rs:575:24
   7: arrow2_convert::serialize::arrow_serialize_extend_internal
             at /home/dourai01/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2_convert-0.3.2/src/serialize.rs:328:9
   8: arrow2_convert::serialize::arrow_serialize_to_mutable_array
             at /home/dourai01/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2_convert-0.3.2/src/serialize.rs:343:5
   9: <Collection as arrow2_convert::serialize::TryIntoArrow<alloc::boxed::Box<dyn arrow2::array::Array>,Element>>::try_into_arrow
             at /home/dourai01/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2_convert-0.3.2/src/serialize.rs:427:12
```

This crashes in debug, and compiling in --release mode silently leads to a corrupted file that pyarrow chokes on when using `pyarrow.compute.struct_field`:
```
pyarrow.lib.ArrowIndexError: Index -1 out of bounds
```

**Comment by douglas-raillard-arm** [comment]
Also note that I ended up triggering this crash by simply modifying the amount of data I was working with while investigating another issue: a corrupted value in pyarrow's `UnionArray.type_codes` array for the dense union (this `type_codes` int8 array encodes the variant of the enum).

When I switched to sparse enum, both the corruption and this crash went away.

**Comment by jorgecarleitao** [comment]
Thanks a lot for this! 

I suspect that this is a bug in arrow2 - we should check that there are less than `i8::MAX` different variants, and not just uncheckly add 1 as we construct the UnionArray.

**Comment by douglas-raillard-arm** [comment]
It sounds like a good idea but there definitely is less than 255 variants in my case, less than 10 actually.

**Comment by ncpenke** [comment]
Thanks for filing this @douglas-raillard-arm. I can also help investigate this @jorgecarleitao. I'm hoping to free up soon, has been very tight on time.
